# Generated by Django 5.0.1 on 2024-03-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Название в адресной строке')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('finish', models.DateTimeField(verbose_name='Конец')),
                ('lab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='interface.lab', verbose_name='Лабораторная работа')),
                ('platoons', models.ManyToManyField(to='interface.platoon')),
            ],
            options={
                'verbose_name': 'Соревнование',
                'verbose_name_plural': 'Соревнования',
            },
        ),
    ]
