# Generated by Django 5.0.3 on 2024-04-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.IntegerField(null=True, verbose_name='Количество участников'),
        ),
    ]
