# Generated by Django 5.0.3 on 2024-04-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_alter_competition_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='participants',
            field=models.IntegerField(default=0, null=True, verbose_name='Количество участников'),
        ),
    ]
