# Generated by Django 5.0.1 on 2024-03-02 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_answers_datetime_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedLabs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(verbose_name='Дата назначения')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('done', models.BooleanField(verbose_name='Завершено')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_for_issue', to='interface.lab')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Назначенная работа',
                'verbose_name_plural': 'Назначенные работы',
            },
        ),
    ]
