# Generated by Django 4.2.9 on 2024-03-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_issuedlabs'),
        ('interface', '0003_issuedlabs'),
    ]

    operations = [
    ]
