# Generated by Django 5.0.3 on 2024-10-27 16:48

import interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_alter_competition_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AddField(
            model_name='lab',
            name='Connectors2CloudData',
            field=models.JSONField(default=interface.models.default_json, verbose_name='Данные облачных коннекторов'),
        ),
        migrations.AddField(
            model_name='lab',
            name='ConnectorsData',
            field=models.JSONField(default=interface.models.default_json, verbose_name='Данные коннекторов'),
        ),
        migrations.AddField(
            model_name='lab',
            name='NetworksData',
            field=models.JSONField(default=interface.models.default_json, verbose_name='Данные сетей'),
        ),
        migrations.AddField(
            model_name='lab',
            name='NodesData',
            field=models.JSONField(default=interface.models.default_json, verbose_name='Данные ноды'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='platoons',
            field=models.ManyToManyField(to='interface.platoon', verbose_name='Взвода'),
        ),
    ]
