# Generated by Django 5.0.3 on 2024-11-09 20:27

import interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_alter_lab_connectors2clouddata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='platform',
            field=models.CharField(choices=interface.models.get_platform_choices, default='NO', max_length=3),
        ),
    ]
