# Generated by Django 5.0.3 on 2024-11-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_alter_lablevel_options_labtask_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedlabs',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued', to='interface.lablevel', verbose_name='Вариант'),
        ),
        migrations.AddField(
            model_name='issuedlabs',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='interface.labtask', verbose_name='Задания'),
        ),
    ]
