# Generated by Django 5.0.3 on 2024-11-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_issuedlabs_level_issuedlabs_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedlabs',
            name='date_of_appointment',
            field=models.DateTimeField(verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='issuedlabs',
            name='end_date',
            field=models.DateTimeField(verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='issuedlabs',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_for_issue', to='interface.lab', verbose_name='Лабораторная работа'),
        ),
    ]
