# Generated by Django 5.0.3 on 2025-01-16 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_alter_issuedlabs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='issued_labs',
            field=models.ManyToManyField(blank=True, null=True, to='interface.issuedlabs'),
        ),
        migrations.AddField(
            model_name='competition',
            name='non_platoon_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Взвода'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='interface.lablevel', verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='issuedlabs',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issued', to='interface.lablevel', verbose_name='Вариант'),
        ),
        migrations.CreateModel(
            name='Competition2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_users', to='interface.competition')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.lablevel', verbose_name='Вариант')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_competitions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
