# Generated by Django 5.0.3 on 2025-01-16 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_competition_issued_labs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='lab_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_task', to='interface.labtask'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='issued_labs',
            field=models.ManyToManyField(blank=True, to='interface.issuedlabs'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='non_platoon_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='platoons',
            field=models.ManyToManyField(blank=True, to='interface.platoon', verbose_name='Взвода'),
        ),
    ]
