# Generated by Django 5.0.3 on 2025-01-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_answers_lab_task_alter_competition_issued_labs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pnet_login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя в Pnet'),
        ),
    ]
