# Generated by Django 5.0.3 on 2025-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_user_pnet_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='issued_labs',
        ),
        migrations.AddField(
            model_name='competition2user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
