# Generated by Django 5.0.3 on 2025-02-02 20:47

import interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_remove_competition_issued_labs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='platform',
            field=models.CharField(choices=interface.models.get_platform_choices, default='NO', max_length=3, verbose_name='Платформа'),
        ),
    ]
