# Generated by Django 5.0.3 on 2025-02-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_alter_lab_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Название в адресной строке'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Название в адресной строке'),
        ),
    ]
