# Generated by Django 5.0.3 on 2025-03-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_teamcompetition_alter_competition2user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.team'),
        ),
    ]
