# Generated by Django 5.0.3 on 2025-02-20 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_alter_competition_slug_alter_lab_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition2user',
            options={'verbose_name': 'Задание участника', 'verbose_name_plural': 'Задания участников'},
        ),
        migrations.AlterField(
            model_name='platoon',
            name='number',
            field=models.IntegerField(unique=True, verbose_name='Номер взвода'),
        ),
        migrations.AddField(
            model_name='teamcompetition',
            name='teams',
            field=models.ManyToManyField(blank=True, through='interface.TeamCompetition2Team', to='interface.team', verbose_name='Команды'),
        ),
    ]
