# Generated by Django 5.0.3 on 2025-02-25 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_teamcompetition_alter_competition2user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition2user',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='competition2user',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_users', to='interface.competition'),
        ),
    ]
