# Generated by Django 5.0.3 on 2025-02-25 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def column_exists(cursor, db_table, column_name, vendor):
    """
    Проверяет существование колонки в зависимости от типа БД.
    """
    if vendor == 'postgresql':
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s
        """, [db_table, column_name])
        return cursor.fetchone() is not None
    elif vendor == 'sqlite':
        # Для SQLite PRAGMA используем имя таблицы в квадратных скобках для безопасности
        cursor.execute(f"PRAGMA table_info([{db_table}])")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns
    else:
        # Для других БД пытаемся добавить поле и ловим ошибку
        # Это не идеально, но работает для большинства случаев
        return False


def add_done_field_if_not_exists(apps, schema_editor):
    """
    Добавляет поле 'done' только если оно еще не существует в базе данных.
    """
    db_table = 'interface_competition2user'
    column_name = 'done'
    vendor = schema_editor.connection.vendor
    quoted_table = schema_editor.connection.ops.quote_name(db_table)
    
    with schema_editor.connection.cursor() as cursor:
        # Проверяем существование колонки
        if not column_exists(cursor, db_table, column_name, vendor):
            # Колонка не существует, добавляем её
            if vendor == 'sqlite':
                # SQLite использует INTEGER для boolean (0/1)
                cursor.execute(f"""
                    ALTER TABLE {quoted_table} 
                    ADD COLUMN done INTEGER NOT NULL DEFAULT 0
                """)
            else:
                cursor.execute(f"""
                    ALTER TABLE {quoted_table} 
                    ADD COLUMN done BOOLEAN NOT NULL DEFAULT FALSE
                """)


def remove_done_field_if_exists(apps, schema_editor):
    """
    Удаляет поле 'done' если оно существует (для отката миграции).
    """
    db_table = 'interface_competition2user'
    column_name = 'done'
    vendor = schema_editor.connection.vendor
    quoted_table = schema_editor.connection.ops.quote_name(db_table)
    
    with schema_editor.connection.cursor() as cursor:
        # Проверяем существование колонки
        if column_exists(cursor, db_table, column_name, vendor):
            # Колонка существует, удаляем её
            if vendor == 'sqlite':
                # SQLite не поддерживает DROP COLUMN напрямую до версии 3.35.0
                # Но для тестов это не критично, так как тестовая БД пересоздается
                try:
                    cursor.execute(f"""
                        ALTER TABLE {quoted_table} 
                        DROP COLUMN done
                    """)
                except Exception:
                    # Если не поддерживается, просто пропускаем
                    pass
            else:
                cursor.execute(f"""
                    ALTER TABLE {quoted_table} 
                    DROP COLUMN done
                """)


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_teamcompetition_alter_competition2user_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_done_field_if_not_exists,
            remove_done_field_if_exists,
        ),
        migrations.AlterField(
            model_name='competition2user',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competition_users', to='interface.competition'),
        ),
    ]
