# Generated by Django 5.0.3 on 2025-03-08 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0019_alter_answers_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='num_tasks',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество заданий для распределения'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.team'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
