# Generated by Django 5.0.3 on 2025-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_competition_num_tasks_alter_answers_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='num_tasks',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество заданий для распределения'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Название в адресной строке'),
        ),
    ]
