# Generated by Django 5.0.3 on 2025-03-09 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_competition2user_done_competition2user_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='num_tasks',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество заданий для распределения'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='answers',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='interface_answers_exclusive_user_team'),
        ),
    ]
