# Generated by Django 5.0.3 on 2025-03-09 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def column_exists(cursor, db_table, column_name, vendor):
    """Проверяет существование колонки в зависимости от типа БД."""
    if vendor == 'postgresql':
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name=%s AND column_name=%s
        """, [db_table, column_name])
        return cursor.fetchone() is not None
    elif vendor == 'sqlite':
        cursor.execute(f"PRAGMA table_info([{db_table}])")
        columns = [row[1] for row in cursor.fetchall()]
        return column_name in columns
    return False


def add_num_tasks_if_not_exists(apps, schema_editor):
    """Добавляет поле num_tasks только если оно еще не существует."""
    db_table = 'interface_competition'
    column_name = 'num_tasks'
    vendor = schema_editor.connection.vendor
    quoted_table = schema_editor.connection.ops.quote_name(db_table)
    
    with schema_editor.connection.cursor() as cursor:
        if not column_exists(cursor, db_table, column_name, vendor):
            cursor.execute(f"""
                ALTER TABLE {quoted_table} 
                ADD COLUMN num_tasks INTEGER NOT NULL DEFAULT 1
            """)


def remove_num_tasks_if_exists(apps, schema_editor):
    """Удаляет поле num_tasks если оно существует."""
    db_table = 'interface_competition'
    column_name = 'num_tasks'
    vendor = schema_editor.connection.vendor
    quoted_table = schema_editor.connection.ops.quote_name(db_table)
    
    with schema_editor.connection.cursor() as cursor:
        if column_exists(cursor, db_table, column_name, vendor):
            try:
                cursor.execute(f"ALTER TABLE {quoted_table} DROP COLUMN num_tasks")
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_competition2user_done_competition2user_tasks_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_num_tasks_if_not_exists,
            remove_num_tasks_if_exists,
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='answers',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('team__isnull', True), ('user__isnull', False)), models.Q(('team__isnull', False), ('user__isnull', True)), _connector='OR'), name='interface_answers_exclusive_user_team'),
        ),
    ]
