# Generated by Django 5.0.3 on 2025-03-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_answers_team_competition_num_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='num_tasks',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество заданий для распределения'),
        ),
    ]
