# Generated by Django 5.0.3 on 2025-07-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0021_alter_competition_num_tasks_alter_lab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='program',
            field=models.CharField(choices=[('ZIT', 'ЗИТ'), ('INFOBOR', 'Инфорбор')], default='ZIT', max_length=10, verbose_name='Образовательная программа'),
        ),
    ]
