# Generated by Django 5.0.3 on 2025-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_alter_competition_num_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Название в адресной строке'),
        ),
    ]
