# Generated by Django 5.0.3 on 2025-07-31 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0022_lab_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='program',
            field=models.CharField(choices=[('INFOBOR', 'Информационное противоборство'), ('COMPETITION', 'Соревнования')], default='INFOBOR', max_length=32, verbose_name='Образовательная программа'),
        ),
    ]
