# Generated by Django 5.0.3 on 2025-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_alter_lab_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='icon',
            field=models.CharField(default='fas fa-laptop-code', help_text='FontAwesome класс иконки', max_length=50, verbose_name='Иконка'),
        ),
    ]
