# Generated by Django 5.0.3 on 2025-07-31 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0024_lab_icon'),
    ]

    operations = [
    ]
