# Generated by Django 5.0.3 on 2025-07-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0026_change_lab_primary_key'),
        ('interface', '0027_change_lab_primary_key'),
    ]

    operations = [
    ]
