# Generated by Django 5.0.3 on 2025-08-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0028_merge_20250731_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Название в адресной строке'),
        ),
    ]
