# Generated by Django 5.0.3 on 2025-08-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0032_cleanup_orphaned_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='icon',
        ),
        migrations.AddField(
            model_name='lab',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='lab_covers/', verbose_name='Обложка'),
        ),
    ]
