# Generated by Django 5.0.3 on 2025-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0033_remove_lab_icon_lab_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='interface.Lab/cover/content/mimetype/filename/', verbose_name='Обложка'),
        ),
    ]
