# Generated by Django 5.0.3 on 2025-08-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0034_alter_lab_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='interface.DBFile/bytes/filename/mimetype', verbose_name='Обложка'),
        ),
    ]
