# Generated by Django 5.0.3 on 2025-08-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0035_dbfile_alter_lab_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DBFile',
        ),
        migrations.AlterField(
            model_name='lab',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='interface/labs/covers/', verbose_name='Обложка'),
        ),
    ]
