# Generated by Django 5.0.3 on 2025-08-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0036_delete_dbfile_alter_lab_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedlabs',
            name='lab',
        ),
        migrations.RemoveField(
            model_name='issuedlabs',
            name='level',
        ),
        migrations.RemoveField(
            model_name='issuedlabs',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='issuedlabs',
            name='user',
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('HW', 'Домашнее задание'), ('EXAM', 'Экзамен'), ('PZ', 'Практическое занятие')], default='HW', max_length=32, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='program',
            field=models.CharField(choices=[('INFOBOR', 'Информационное противоборство'), ('COMPETITION', 'Соревнования'), ('CMD', 'Командная строка')], default='INFOBOR', max_length=32, verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Название в адресной строке'),
        ),
        migrations.AddConstraint(
            model_name='lab',
            constraint=models.UniqueConstraint(fields=('slug', 'lab_type'), name='unique_slug_labtype'),
        ),
        migrations.DeleteModel(
            name='IssuedLabs',
        ),
    ]
