# Generated by Django 5.0.3 on 2025-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0037_remove_issuedlabs_lab_remove_issuedlabs_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='learning_years',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Годы обучения'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('HW', 'Домашнее задание'), ('EXAM', 'Экзамен'), ('PZ', 'Практическое занятие'), ('COMPETITION', 'Соревнование')], default='HW', max_length=32, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='program',
            field=models.CharField(choices=[('INFOBOR', 'Информационное противоборство'), ('COMPETITION', 'Соревнования')], default='INFOBOR', max_length=32, verbose_name='Образовательная программа'),
        ),
    ]
