# Generated by Django 5.0.3 on 2025-08-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0038_lab_learning_years_alter_lab_lab_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoon',
            name='learning_year',
            field=models.IntegerField(choices=[(1, 'Первый'), (2, 'Второй'), (3, 'Третий')], default=1, verbose_name='Год обучения'),
        ),
    ]
