# Generated by Django 5.0.3 on 2025-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0039_platoon_learning_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='default_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Время на работу'),
        ),
    ]
