# Generated by Django 5.0.3 on 2025-08-10 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0040_lab_default_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='default_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=7), null=True, verbose_name='Время на работу'),
        ),
    ]
