# Generated by Django 5.0.3 on 2025-08-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0041_alter_lab_default_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='tasks_type',
            field=models.CharField(choices=[('CLASSIC', 'Обычные'), ('JSON_CONFIGURED', 'Определяемые на вебе')], default='CLASSIC', max_length=32, verbose_name='Тип заданий'),
        ),
    ]
