# Generated by Django 5.0.3 on 2025-08-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0042_lab_tasks_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='json_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Конфигурация задания'),
        ),
    ]
