# Generated by Django 5.0.3 on 2025-08-16 20:44

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0043_labtask_json_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pnet_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль в Pnet'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='tasks_type',
            field=models.CharField(choices=[('CLASSIC', 'Обычные'), ('JSON_CONFIGURED', 'C JSON-конфигурацией')], default='CLASSIC', max_length=32, verbose_name='Тип заданий'),
        ),
        migrations.AlterField(
            model_name='labtask',
            name='json_config',
            field=models.JSONField(blank=True, default=dict, help_text="JSON-конфигурация с полями: task_type ('input' или 'state'), answer, regex", null=True, validators=[interface.validators.validate_lab_task_json_config], verbose_name='Конфигурация задания'),
        ),
    ]
