# Generated by Django 5.0.3 on 2025-09-05 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0023_alter_lab_slug'),
        ('interface', '0044_user_pnet_password_alter_lab_tasks_type_and_more'),
    ]

    operations = [
    ]
