# Generated by Django 5.0.3 on 2025-09-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0046_fix_lab_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
