# Generated by Django 5.0.3 on 2025-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0047_alter_lab_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='need_kibana',
            field=models.BooleanField(default=False, verbose_name='Показывать дашборд в Kibana'),
        ),
    ]
