# Generated by Django 5.0.3 on 2025-09-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0047_alter_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('HW', 'Домашнее задание'), ('EXAM', 'Экзамен'), ('PZ', 'Практическое занятие'), ('COMPETITION', 'Соревнование')], max_length=32, verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='program',
            field=models.CharField(choices=[('INFOBOR', 'Информационное противоборство'), ('COMPETITION', 'Соревнования')], max_length=32, verbose_name='Образовательная программа'),
        ),
    ]
