# Generated by Django 5.0.3 on 2025-09-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0048_alter_lab_lab_type_alter_lab_program'),
        ('interface', '0048_lab_need_kibana'),
    ]

    operations = [
    ]
