# Generated by Django 5.0.3 on 2025-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0049_merge_20250920_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='PnetSSHNodeName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя ноды в Pnet для SSH'),
        ),
    ]
