# Generated by Django 5.0.3 on 2025-09-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0049_merge_20250919_1327'),
        ('interface', '0050_lab_pnetsshnodename'),
    ]

    operations = [
    ]
