# Generated by Django 5.0.3 on 2025-01-XX XX:XX

from django.db import migrations, models


def populate_pnet_slug(apps, schema_editor):
    """
    Заполняем поле pnet_slug значениями из slug для всех существующих Lab
    """
    Lab = apps.get_model('interface', 'Lab')

    for lab in Lab.objects.all():
        if not lab.pnet_slug:  # Заполняем только если pnet_slug пустой
            lab.pnet_slug = lab.slug
            lab.save(update_fields=['pnet_slug'])


def reverse_populate_pnet_slug(apps, schema_editor):
    """
    Обратная операция - очищаем pnet_slug
    """
    Lab = apps.get_model('interface', 'Lab')

    for lab in Lab.objects.all():
        lab.pnet_slug = ''
        lab.save(update_fields=['pnet_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0050_lab_pnetsshnodename'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='pnet_slug',
            field=models.SlugField(
                blank=True,
                max_length=255,
                verbose_name='Ключ лабы в API (lab_slug)'
            ),
        ),
        migrations.RunPython(
            populate_pnet_slug,
            reverse_populate_pnet_slug,
        ),
    ]