# Generated by Django 5.0.3 on 2025-09-20 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_primary_key_constraint(apps, schema_editor):
    """
    Add PRIMARY KEY constraint to interface_lab table if it doesn't exist
    """
    vendor = schema_editor.connection.vendor
    db_table = 'interface_lab'
    quoted_table = schema_editor.connection.ops.quote_name(db_table)
    
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            # Проверяем, есть ли уже первичный ключ
            cursor.execute("""
                SELECT constraint_name 
                FROM information_schema.table_constraints 
                WHERE table_name = %s 
                AND constraint_type = 'PRIMARY KEY'
            """, [db_table])
            
            if not cursor.fetchone():
                cursor.execute(f"ALTER TABLE {quoted_table} ADD CONSTRAINT interface_lab_pkey PRIMARY KEY (id);")
        elif vendor == 'sqlite':
            # SQLite doesn't support adding PRIMARY KEY to existing table
            # We'll create a unique index instead
            cursor.execute(f"CREATE UNIQUE INDEX IF NOT EXISTS interface_lab_pkey ON {quoted_table}(id);")


def remove_primary_key_constraint(apps, schema_editor):
    """
    Remove PRIMARY KEY constraint from interface_lab table
    """
    vendor = schema_editor.connection.vendor
    db_table = 'interface_lab'
    quoted_table = schema_editor.connection.ops.quote_name(db_table)
    
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'postgresql':
            try:
                cursor.execute(f"ALTER TABLE {quoted_table} DROP CONSTRAINT IF EXISTS interface_lab_pkey;")
            except Exception:
                pass
        elif vendor == 'sqlite':
            cursor.execute("DROP INDEX IF EXISTS interface_lab_pkey;")


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0051_alter_lab_pnetsshnodename'),
    ]

    operations = [
        # First, add PRIMARY KEY constraint to interface_lab table
        migrations.RunPython(
            add_primary_key_constraint,
            remove_primary_key_constraint
        ),
        # Then create the KkzPreview model
        migrations.CreateModel(
            name='KkzPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='interface.kkz')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkz_previews', to='interface.lab')),
                ('tasks', models.ManyToManyField(blank=True, to='interface.labtask', verbose_name='Задания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Превью распределения ККЗ',
                'verbose_name_plural': 'Превью распределений ККЗ',
            },
        ),
    ]
