# Generated by Django 5.0.3 on 2025-09-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0051_merge_20250920_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='PnetSSHNodeName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя ноды в Pnet для открытия консоли'),
        ),
    ]
