# Generated by Django 5.0.3 on 2025-09-20 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def add_primary_key_constraint(apps, schema_editor):
    """
    Add PRIMARY KEY constraint to interface_lab table
    """
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE interface_lab ADD CONSTRAINT interface_lab_pkey PRIMARY KEY (id);")
    elif connection.vendor == 'sqlite':
        # SQLite doesn't support adding PRIMARY KEY to existing table
        # We'll create a unique index instead
        with connection.cursor() as cursor:
            cursor.execute("CREATE UNIQUE INDEX IF NOT EXISTS interface_lab_pkey ON interface_lab(id);")


def remove_primary_key_constraint(apps, schema_editor):
    """
    Remove PRIMARY KEY constraint from interface_lab table
    """
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE interface_lab DROP CONSTRAINT interface_lab_pkey;")
    elif connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("DROP INDEX IF EXISTS interface_lab_pkey;")


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0051_alter_lab_pnetsshnodename'),
    ]

    operations = [
        # First, add PRIMARY KEY constraint to interface_lab table
        migrations.RunPython(
            add_primary_key_constraint,
            remove_primary_key_constraint
        ),
        # Then create the KkzPreview model
        migrations.CreateModel(
            name='KkzPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='interface.kkz')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkz_previews', to='interface.lab')),
                ('tasks', models.ManyToManyField(blank=True, to='interface.labtask', verbose_name='Задания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Превью распределения ККЗ',
                'verbose_name_plural': 'Превью распределений ККЗ',
            },
        ),
    ]
