# Generated by Django 5.0.3 on 2025-09-20 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0051_alter_lab_pnetsshnodename'),
    ]

    operations = [
        migrations.CreateModel(
            name='KkzPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kkz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='interface.kkz')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kkz_previews', to='interface.lab')),
                ('tasks', models.ManyToManyField(blank=True, to='interface.labtask', verbose_name='Задания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Превью распределения ККЗ',
                'verbose_name_plural': 'Превью распределений ККЗ',
            },
        ),
    ]
