# Generated by Django 5.0.3 on 2025-10-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0051_add_pnet_slug'),
        ('interface', '0052_kkzpreview'),
    ]

    operations = [
    ]
