# Generated by Django 5.0.3 on 2025-09-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0051_add_pnet_slug'),
        ('interface', '0052_alter_lab_pnetsshnodename'),
    ]

    operations = [
    ]
