# Generated by Django 5.0.3 on 2025-10-11 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0053_merge_0051_add_pnet_slug_0052_kkzpreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
