# Generated by Django 5.0.3 on 2025-10-11 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0053_merge_0051_add_pnet_slug_0052_kkzpreview'),
        ('interface', '0053_merge_20250928_1026'),
    ]

    operations = [
    ]
