# Generated by Django 5.0.3 on 2025-10-11 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0054_competition_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
