# Generated by Django 5.0.3 on 2025-10-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0055_alter_competition_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='labtask',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='tasks_type',
            field=models.CharField(choices=[('CLASSIC', 'Обычные'), ('JSON_CONFIGURED', 'C JSON-конфигурацией'), ('TESTING', 'В форме тестирования')], default='CLASSIC', max_length=32, verbose_name='Тип заданий'),
        ),
    ]
