# Generated by Django 5.0.3 on 2025-10-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0056_labtask_answer_labtask_question_alter_lab_tasks_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition2user',
            name='done',
        ),
        migrations.AlterField(
            model_name='labtask',
            name='answer',
            field=models.TextField(blank=True, help_text='Правильный ответ на вопрос или регулярное выражение для проверки ответа', null=True, verbose_name='Ответ'),
        ),
    ]
