# Generated by Django 5.0.3 on 2025-11-08 17:18

import django.core.validators
import django.db.models.deletion
import django_summernote.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0057_remove_competition2user_done_alter_labtask_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myattachment',
            name='file',
            field=models.FileField(upload_to=django_summernote.utils.uploaded_filepath, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip', 'rar', 'txt'])]),
        ),
        migrations.CreateModel(
            name='LabNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=255, verbose_name='Имя Ноды')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='interface.lab')),
            ],
            options={
                'verbose_name': 'Нода для SSH флагов',
                'verbose_name_plural': 'Ноды для SSH флагов',
            },
        ),
    ]
