# Generated by Django 5.0.3 on 2025-10-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0057_alter_labtask_answer'),
        ('interface', '0057_remove_competition2user_done_alter_labtask_answer'),
    ]

    operations = [
    ]
