# Generated by Django 5.0.3 on 2025-11-08 19:58

import interface.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0058_alter_myattachment_file_labnode'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition2user',
            name='generated_flags',
            field=models.JSONField(blank=True, default=list, null=True, validators=[interface.validators.validate_top_level_array], verbose_name='Сгенерированные флаги'),
        ),
        migrations.AddField(
            model_name='teamcompetition2team',
            name='generated_flags',
            field=models.JSONField(blank=True, default=list, null=True, validators=[interface.validators.validate_top_level_array], verbose_name='Сгенерированные флаги'),
        ),
    ]
