# Generated by Django 5.0.3 on 2025-11-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0058_merge_20251024_1758'),
        ('interface', '0059_competition2user_generated_flags_and_more'),
    ]

    operations = [
    ]
