# Generated by Django 5.0.3 on 2025-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0059_competition2user_generated_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition2user',
            name='deploy_meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Метаданные развертывания'),
        ),
        migrations.AddField(
            model_name='teamcompetition2team',
            name='deploy_meta',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Метаданные развертывания'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='program',
            field=models.CharField(choices=[('INFOBOR', 'Информационное противоборство'), ('COMPETITION', 'Соревнования'), ('STUDENT_WORKS', 'Работы студентов')], max_length=32, verbose_name='Образовательная программа'),
        ),
    ]
