# Generated by Django 5.0.3 on 2025-11-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0060_competition2user_deploy_meta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Назначенная работа', 'verbose_name_plural': 'Назначенные работы'},
        ),
    ]
