# Generated by Django 5.0.3 on 2025-11-13 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0060_competition2user_deploy_meta_and_more'),
        ('interface', '0060_merge_20251109_1725'),
    ]

    operations = [
    ]
