# Generated by Django 5.0.3 on 2025-11-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0060_competition2user_deploy_meta_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Назначенная работа', 'verbose_name_plural': 'Назначенные работы'},
        ),
        migrations.AlterModelOptions(
            name='labtask',
            options={'ordering': ['task_id'], 'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
