# Generated by Django 5.0.3 on 2025-11-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0061_alter_competition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='failing_tasks',
            field=models.BooleanField(default=False, verbose_name='Одна попытка на задание'),
        ),
    ]
