# Generated by Django 5.0.3 on 2025-11-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0061_merge_20251113_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Работа', 'verbose_name_plural': 'Работы'},
        ),
    ]
