# Generated by Django 5.0.3 on 2025-11-23 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0062_lab_failing_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='failing_tasks',
        ),
        migrations.AddField(
            model_name='competition2user',
            name='failed_tasks',
            field=models.JSONField(blank=True, default=list, help_text='Список ID заданий, на которые пользователь больше не может отвечать', null=True, verbose_name='Задания с неверным ответом (PK заданий, на которые больше нельзя отвечать)'),
        ),
        migrations.AddField(
            model_name='lab',
            name='task_checking',
            field=models.CharField(choices=[('MULTIPLE_ATTEMPTS', 'Несколько попыток'), ('ONE_ATTEMPT', 'Одна попытка')], default='MULTIPLE_ATTEMPTS', max_length=32, verbose_name='Метод проверки заданий'),
        ),
        migrations.AddField(
            model_name='teamcompetition2team',
            name='failed_tasks',
            field=models.JSONField(blank=True, default=list, help_text='Список ID заданий, на которые команда больше не может отвечать', null=True, verbose_name='Задания с неверным ответом (PK заданий, на которые больше нельзя отвечать)'),
        ),
    ]
