# Generated by Django 5.0.3 on 2025-11-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0062_alter_competition_options'),
        ('interface', '0063_remove_lab_failing_tasks_and_more'),
    ]

    operations = [
    ]
