# Generated by Django 5.0.3 on 2025-11-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0064_merge_20251123_2317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Назначенная работа', 'verbose_name_plural': 'Назначенные работы'},
        ),
    ]
