# Generated by Django 5.0.3 on 2025-11-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0061_alter_competition_options_alter_labtask_options'),
        ('interface', '0065_alter_competition_options'),
    ]

    operations = [
    ]
