# Generated by Django 5.0.3 on 2025-11-30 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0066_merge_20251127_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='default_duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(days=1), null=True, verbose_name='Время на работу'),
        ),
    ]
