# Generated by Django 5.0.3 on 2025-12-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0067_alter_lab_default_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtask',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
    ]
