# Generated by Django 5.0.3 on 2025-12-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0068_alter_labtask_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='interface.lab', verbose_name='Лабораторная работа')),
            ],
            options={
                'verbose_name': 'Тип задания',
                'verbose_name_plural': 'Типы заданий',
                'unique_together': {('lab', 'name')},
            },
        ),
        migrations.AddField(
            model_name='labtask',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='interface.labtasktype', verbose_name='Тип задания'),
        ),
        migrations.CreateModel(
            name='CompetitionTaskTypeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество заданий')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_type_counts', to='interface.competition')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.labtasktype', verbose_name='Тип задания')),
            ],
            options={
                'verbose_name': 'Количество заданий по типу',
                'verbose_name_plural': 'Количество заданий по типам',
                'unique_together': {('competition', 'task_type')},
            },
        ),
    ]
