# Generated by Django 5.0.3 on 2025-12-09 13:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0068_alter_labtask_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='interface/labs/backgrounds/', verbose_name='Фоновое изображение'),
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_elements_color',
            field=colorfield.fields.ColorField(default='#ffffff', help_text='Цвет подложки и инпутов формы (по умолчанию белый).', image_field=None, max_length=25, samples=None, verbose_name='Цвет элементов формы'),
        ),
    ]
