# Generated by Django 5.0.3 on 2025-12-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0069_lab_background_image_lab_lab_elements_color'),
        ('interface', '0069_labtasktype_labtask_task_type_and_more'),
    ]

    operations = [
    ]
