# Generated by Django 5.0.3 on 2025-12-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0070_merge_20251209_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtasktype',
            name='default_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300), help_text='Время, которое дается на выполнение одного задания этого типа', verbose_name='Время на выполнение (одного задания)'),
        ),
    ]
