# Generated by Django 5.0.3 on 2026-01-24 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0071_labtasktype_default_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcompetition2team',
            name='master_session_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_team_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь мастер-сессии'),
        ),
    ]
