# Generated by Django 5.0.3 on 2026-01-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0072_teamcompetition2team_master_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcompetition2team',
            name='master_session_created',
            field=models.BooleanField(default=False, verbose_name='Мастер-сессия создана'),
        ),
    ]
