# Generated by Django 5.0.3 on 2026-01-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0073_teamcompetition2team_master_session_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition2user',
            name='joined',
            field=models.BooleanField(default=False, help_text='True, если студент заходил на страницу задания (показывается в таблице лидеров)', verbose_name='Подключился к заданию'),
        ),
        migrations.AddField(
            model_name='teamcompetition2team',
            name='joined',
            field=models.BooleanField(default=False, help_text='True, если команда заходила на страницу соревнования (показывается в таблице лидеров)', verbose_name='Подключилась к лабе'),
        ),
    ]
