# Generated by Django 5.0.3 on 2026-01-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0073_teamcompetition2team_master_session_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='need_iframe_for_admin',
            field=models.BooleanField(default=True, verbose_name='Выдавать преподавателю сессию в PNEt'),
        ),
    ]
