# Generated by Django 5.0.3 on 2026-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0074_lab_need_iframe_for_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtask',
            name='dependencies',
            field=models.CharField(blank=True, help_text='Вводите идентификаторы через запятую', max_length=1023, null=True, verbose_name='Идентификаторы заданий-зависимостей'),
        ),
    ]
