# Generated by Django 5.0.3 on 2026-01-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0074_competition2user_joined_teamcompetition2team_joined'),
        ('interface', '0075_labtask_dependencies'),
    ]

    operations = [
    ]
