# Generated by Django 5.0.3 on 2026-02-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0076_merge_20260131_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition2user',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='teamcompetition2team',
            name='grade',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
