# Generated by Django 5.0.3 on 2026-02-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0077_competition2user_grade_teamcompetition2team_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='kibana_dashboard',
            field=models.CharField(choices=[('SURICATA', 'Suricata'), ('SNORT', 'Snort')], default='SURICATA', max_length=32, verbose_name='Тип дашборда'),
        ),
    ]
