# Generated by Django 5.0.3 on 2026-02-19 21:17

import django.db.models.deletion
import interface.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0078_lab_kibana_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='TopologySegmentsData',
            field=models.JSONField(default=list, help_text='Сегменты: [{"name": "Сегмент 1", "vm_names": ["vm1", "vm2"]}, ...]', validators=[interface.validators.validate_top_level_array], verbose_name='Сегменты топологии'),
        ),
        migrations.CreateModel(
            name='TeamCompetition2TeamsAndUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_session_created', models.BooleanField(default=False, verbose_name='Мастер-сессия создана')),
                ('generated_flags', models.JSONField(blank=True, default=list, null=True, validators=[interface.validators.validate_top_level_array], verbose_name='Сгенерированные флаги')),
                ('deploy_meta', models.JSONField(blank=True, default=dict, null=True, verbose_name='Метаданные развертывания')),
                ('failed_tasks', models.JSONField(blank=True, default=list, help_text='Список ID заданий, на которые участники сессии больше не могут отвечать', null=True, verbose_name='Задания с неверным ответом')),
                ('joined', models.BooleanField(default=False, verbose_name='Подключились к лабе')),
                ('grade', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('deleted', models.BooleanField(default=False)),
                ('master_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_segment_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь мастер-сессии')),
                ('tasks', models.ManyToManyField(blank=True, to='interface.labtask', verbose_name='Задания')),
                ('team_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_sessions', to='interface.teamcompetition')),
                ('teams', models.ManyToManyField(blank=True, related_name='team_competition_sessions', to='interface.team', verbose_name='Команды')),
                ('users', models.ManyToManyField(blank=True, related_name='team_competition_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Одиночные пользователи')),
            ],
            options={
                'verbose_name': 'Сессия соревнования',
                'verbose_name_plural': 'Сессии соревнований',
            },
        ),
        migrations.CreateModel(
            name='TopologySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название сегмента')),
                ('vm_names', models.JSONField(default=list, help_text='Список имён VM в формате JSON, например: ["vm1", "vm2"]', verbose_name='Имена VM')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_segments', to='interface.lab', verbose_name='Лабораторная работа')),
            ],
            options={
                'verbose_name': 'Сегмент топологии',
                'verbose_name_plural': 'Сегменты топологии',
                'ordering': ['lab', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamOrUser2Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_assignments', to='interface.team')),
                ('team_competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_assignments', to='interface.teamcompetition')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segment_assignments', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_assignments', to='interface.topologysegment')),
            ],
            options={
                'verbose_name': 'Привязка команды/пользователя к сегменту',
                'verbose_name_plural': 'Привязки команд/пользователей к сегментам',
            },
        ),
        migrations.AddConstraint(
            model_name='teamoruser2segment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('team__isnull', False), ('user__isnull', True)), models.Q(('team__isnull', True), ('user__isnull', False)), _connector='OR'), name='interface_teamoruser2segment_exclusive_team_user'),
        ),
    ]
