# Generated by Django 5.0.3 on 2026-02-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0079_lab_topologysegmentsdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcompetition2teamsandusers',
            name='segment_pnet_session_id',
            field=models.CharField(blank=True, help_text='Кто первый открыл лабу — в его сессии создана; остальные джойнятся по этому id', max_length=64, null=True, verbose_name='PNET session_id сегмента'),
        ),
        migrations.AddField(
            model_name='teamcompetition2teamsandusers',
            name='segment_pnet_session_owner_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='user_id владельца PNET-сессии сегмента'),
        ),
    ]
